library(shiny.semantic)
library(shiny)
library(magrittr)
library(highlighter) # devtools::install_github("Appsilon/highlighter")
library(formatR)
library(httr)
library(rjson)
library(dplyr)
library(shinyjs)
library(leaflet)
library(geosphere)
library(vroom)
library(readr)
library(shinyWidgets)
library(shiny.router)
library(shinyalert)
library(shinycssloaders)
library(DT)
